name: Deploy to dev WP Engine
on:
    push:
        branches:
            - dev
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: GitHub Action Deploy to WP Engine
              uses: wpengine/github-action-wpe-site-deploy@v3
              with:
                  # Deploy vars
                  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
                  WPE_ENV: falconhunter
                  # Deploy Options
                  # SRC_PATH: "wp-content/plugins/"
                  REMOTE_PATH: 'wp-content/plugins/gutenberg-starter/'
                  # PHP_LINT: TRUE
                  # FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
                  # SCRIPT: "path/yourscript.sh"
                  # CACHE_CLEAR: TRUE
